//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CactusGuru.Persistance.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSeedListItem
    {
        public System.Guid Id { get; set; }
        public System.Guid tblSeedListId { get; set; }
        public int Type { get; set; }
        public string Code { get; set; }
        public int StandardPocketCount { get; set; }
        public int StandardPocketPrice { get; set; }
        public Nullable<int> Pocket100sPrice { get; set; }
        public Nullable<int> Pocket500sPrice { get; set; }
        public Nullable<int> Pocket1000sPrice { get; set; }
        public Nullable<System.Guid> tblCollectionItemId { get; set; }
        public Nullable<System.Guid> tblTaxonId { get; set; }
        public Nullable<System.Guid> tblSupplierId { get; set; }
        public string SupplierCode { get; set; }
    
        public virtual tblCollectionItem tblCollectionItem { get; set; }
        public virtual tblSeedList tblSeedList { get; set; }
        public virtual tblSupplier tblSupplier { get; set; }
        public virtual tblTaxon tblTaxon { get; set; }
    }
}
